export interface ProductReview {
  id: string;
  author: string;
  verified: boolean;
  rating: 5 | 4 | 3;
  date: string;
  title?: string;
  body: string;
  tags: string[];
}

export interface ProductReviewsBundle {
  tags: string[];
  reviews: ProductReview[];
}

const REVIEWS_BY_SLUG: Record<string, ProductReviewsBundle> = {
  "pure-shilajit": {
    tags: [
      "Energy",
      "Authentic",
      "Morning ritual",
      "Quality",
      "Purity",
      "Stamina",
    ],
    reviews: [
      {
        id: "shilajit-1",
        author: "Arjun Mehta",
        verified: true,
        rating: 5,
        date: "03/14/2026",
        title: "Noticeably more energy",
        body: "I take a pea-sized amount with warm water every morning. Within two weeks my afternoon slump disappeared. The resin dissolves cleanly and tastes exactly like real shilajit should — earthy, not sweetened.",
        tags: ["Energy", "Morning ritual", "Quality"],
      },
      {
        id: "shilajit-2",
        author: "Deepa Nair",
        verified: true,
        rating: 5,
        date: "02/02/2026",
        title: "Worth the price",
        body: "Ordered for my husband who runs marathons. He says recovery feels quicker and his legs don't feel as heavy after long runs. Packaging was secure and the jar arrived without any leak.",
        tags: ["Stamina", "Quality"],
      },
      {
        id: "shilajit-3",
        author: "Vikram Singh",
        verified: false,
        rating: 5,
        date: "01/18/2026",
        body: "Third jar now. Consistency is good batch to batch. I appreciate that they share lab testing details — that kind of transparency matters when you're putting something in your body daily.",
        tags: ["Purity", "Authentic"],
      },
      {
        id: "shilajit-4",
        author: "Meera Joshi",
        verified: true,
        rating: 4,
        date: "12/09/2025",
        title: "Strong but genuine",
        body: "Took a few days to get used to the taste mixed in milk. Quality feels premium and I do feel more alert through the workday. Would love a small spoon included in the box.",
        tags: ["Energy", "Quality"],
      },
      {
        id: "shilajit-5",
        author: "Rahul Kulkarni",
        verified: true,
        rating: 5,
        date: "11/22/2025",
        body: "My ayurvedic practitioner recommended shilajit and this brand was on his list. Dissolves well in hot water. No fillers, no weird smell — just pure resin.",
        tags: ["Authentic", "Purity"],
      },
      {
        id: "shilajit-6",
        author: "Sneha Reddy",
        verified: false,
        rating: 5,
        date: "10/05/2025",
        title: "Part of my daily stack",
        body: "Pairs well with my morning routine alongside light exercise. Delivery was on time to Hyderabad and customer support answered my dosage question promptly.",
        tags: ["Morning ritual", "Quality"],
      },
    ],
  },
  "ashwagandha-advance": {
    tags: [
      "Sleep",
      "Stress relief",
      "Focus",
      "Capsules",
      "Calm",
      "Recovery",
    ],
    reviews: [
      {
        id: "ashwa-1",
        author: "Kavitha Menon",
        verified: true,
        rating: 5,
        date: "03/19/2026",
        title: "Sleep finally improved",
        body: "I was waking up at 3am every night from work stress. Two capsules after dinner for three weeks and I'm sleeping through again. No grogginess in the morning either.",
        tags: ["Sleep", "Stress relief", "Calm"],
      },
      {
        id: "ashwa-2",
        author: "Imran Shaikh",
        verified: true,
        rating: 5,
        date: "02/28/2026",
        body: "Desk job, long hours, constant tension headaches. This has taken the edge off without making me feel dull. Easy to swallow capsules — no aftertaste.",
        tags: ["Stress relief", "Focus", "Capsules"],
      },
      {
        id: "ashwa-3",
        author: "Pooja Agarwal",
        verified: false,
        rating: 5,
        date: "01/30/2026",
        title: "Calmer evenings",
        body: "I take one in the morning and one at night. My family says I'm less irritable after hectic days. Will reorder when this bottle finishes.",
        tags: ["Calm", "Stress relief"],
      },
      {
        id: "ashwa-4",
        author: "Nikhil Desai",
        verified: true,
        rating: 4,
        date: "12/15/2025",
        body: "Good formulation with L-theanine — feels balanced, not overly sedating. Took about ten days to notice a difference. Packaging is clean and professional.",
        tags: ["Focus", "Capsules"],
      },
      {
        id: "ashwa-5",
        author: "Ananya Iyer",
        verified: true,
        rating: 5,
        date: "11/03/2025",
        title: "Post-workout recovery",
        body: "I lift weights four times a week. Adding this to my routine helped with soreness and I feel more recovered between sessions. Verified ingredients list on the label.",
        tags: ["Recovery", "Quality"],
      },
      {
        id: "ashwa-6",
        author: "Harpreet Kaur",
        verified: false,
        rating: 5,
        date: "09/21/2025",
        body: "Recommended by a friend in Pune. Honest product, fair pricing, and delivery was faster than expected. Already on my second bottle.",
        tags: ["Stress relief", "Capsules"],
      },
    ],
  },
  "diabetes-shudhi": {
    tags: [
      "Blood sugar",
      "Ayurvedic",
      "Daily routine",
      "Doctor approved",
      "Natural",
    ],
    reviews: [
      {
        id: "diabetes-1",
        author: "Ramesh Pillai",
        verified: true,
        rating: 5,
        date: "03/08/2026",
        title: "Steadier readings",
        body: "My fasting numbers have been more consistent since I started this alongside my walks and diet changes. My doctor said the ingredient list looks sensible. No side effects so far.",
        tags: ["Blood sugar", "Doctor approved"],
      },
      {
        id: "diabetes-2",
        author: "Lakshmi Venkat",
        verified: true,
        rating: 5,
        date: "02/11/2026",
        body: "Bought for my father. He likes that it's herbal and not another harsh tablet. We track his levels weekly and there's been a gradual improvement over two months.",
        tags: ["Ayurvedic", "Natural"],
      },
      {
        id: "diabetes-3",
        author: "Suresh Bhat",
        verified: false,
        rating: 4,
        date: "01/04/2026",
        title: "Patience required",
        body: "Not an overnight fix — took about six weeks before I noticed better post-meal readings. Taste is mild. I take it before breakfast as suggested on the pack.",
        tags: ["Daily routine", "Blood sugar"],
      },
      {
        id: "diabetes-4",
        author: "Fatima Khan",
        verified: true,
        rating: 5,
        date: "11/29/2025",
        body: "Clear labelling and transparent sourcing info on the website convinced me to try. Capsules are easy to carry when travelling for work.",
        tags: ["Natural", "Ayurvedic"],
      },
      {
        id: "diabetes-5",
        author: "Gopal Sharma",
        verified: true,
        rating: 5,
        date: "10/17/2025",
        title: "Part of my morning",
        body: "I pair it with fenugreek tea and portion control. Energy feels more stable through the day. Har Ghar Shudhi's support team helped with dosage timing.",
        tags: ["Daily routine", "Blood sugar"],
      },
      {
        id: "diabetes-6",
        author: "Revathi Nambiar",
        verified: false,
        rating: 5,
        date: "08/30/2025",
        body: "Reordered twice. Quality has been consistent. Appreciate the Ayurvedic approach without exaggerated claims on the packaging.",
        tags: ["Ayurvedic", "Natural"],
      },
    ],
  },
  "gut-shudhi": {
    tags: [
      "Digestion",
      "Bloating",
      "Gentle",
      "Gut health",
      "Daily use",
    ],
    reviews: [
      {
        id: "gut-1",
        author: "Aditi Malhotra",
        verified: true,
        rating: 5,
        date: "03/02/2026",
        title: "Less bloating after meals",
        body: "I struggle with heaviness after dinner. One capsule before my main meal made a visible difference in ten days. Gentle — no cramping or urgency.",
        tags: ["Bloating", "Digestion", "Gentle"],
      },
      {
        id: "gut-2",
        author: "Mohammed Asif",
        verified: true,
        rating: 5,
        date: "02/06/2026",
        body: "Travel a lot for work and my gut always acted up. This has become a fixed item in my travel pouch. Works better than the antacid cycle I was stuck in.",
        tags: ["Gut health", "Daily use"],
      },
      {
        id: "gut-3",
        author: "Chitra Devi",
        verified: false,
        rating: 5,
        date: "12/28/2025",
        title: "Ayurvedic and effective",
        body: "My nutritionist suggested triphala-based support. This blend feels balanced. Morning routine is smoother and I feel lighter through the day.",
        tags: ["Digestion", "Gentle"],
      },
      {
        id: "gut-4",
        author: "Sanjeev Vermani",
        verified: true,
        rating: 5,
        date: "11/14/2025",
        body: "Ordered from Har Ghar Shudhi after reading their transparency page. Delivered on time, well packed. The product is excellent quality and very gentle for digestion.",
        tags: ["Quality", "Digestion"],
      },
      {
        id: "gut-5",
        author: "Neha Kapoor",
        verified: true,
        rating: 4,
        date: "09/08/2025",
        body: "Took a full month to feel the full benefit. Worth sticking with. Slight herbal taste if you open the capsule — I just swallow whole with water.",
        tags: ["Gut health", "Daily use"],
      },
      {
        id: "gut-6",
        author: "Thomas Varghese",
        verified: false,
        rating: 5,
        date: "07/19/2025",
        title: "Recommended to colleagues",
        body: "Office canteen food wrecked my stomach. Gut Shudhi plus more water helped reset things. Already told two coworkers about it.",
        tags: ["Digestion", "Bloating"],
      },
    ],
  },
  "master-mineral": {
    tags: [
      "Minerals",
      "Daily supplement",
      "Energy",
      "Quality",
      "Immunity",
    ],
    reviews: [
      {
        id: "mineral-1",
        author: "Sandhya Deepak",
        verified: true,
        rating: 5,
        date: "03/11/2026",
        title: "Quality product",
        body: "I was looking for a clean mineral blend without synthetic fillers. This checks the boxes. I add it to my morning smoothie — mixes fine and no chalky aftertaste.",
        tags: ["Minerals", "Quality"],
      },
      {
        id: "mineral-2",
        author: "Amit Bhattacharya",
        verified: true,
        rating: 5,
        date: "02/19/2026",
        body: "Doctor flagged low iron and zinc on my last report. Along with diet changes, this supplement helped bring levels back into range on the follow-up test.",
        tags: ["Daily supplement", "Minerals"],
      },
      {
        id: "mineral-3",
        author: "Priya Sharma",
        verified: false,
        rating: 5,
        date: "01/07/2026",
        title: "Whole family uses it",
        body: "My husband and I both take half a scoop daily. Kids' pediatrician said it's fine for teens too. Honest labelling — you know exactly what's inside.",
        tags: ["Daily supplement", "Quality"],
      },
      {
        id: "mineral-4",
        author: "Rohit Chawla",
        verified: true,
        rating: 4,
        date: "11/30/2025",
        body: "Good product. Jar is smaller than I expected but the concentration seems high so it lasts. Would appreciate a larger family pack option.",
        tags: ["Minerals", "Daily supplement"],
      },
      {
        id: "mineral-5",
        author: "Lalita Ghosh",
        verified: true,
        rating: 5,
        date: "10/12/2025",
        title: "Less fatigue",
        body: "Menopause left me constantly tired. After a month on Master Mineral plus better sleep, I have more stamina for household work and walks.",
        tags: ["Energy", "Immunity"],
      },
      {
        id: "mineral-6",
        author: "Daniel Fernandes",
        verified: false,
        rating: 5,
        date: "08/04/2025",
        body: "Vegetarian formula was important to me. Capsules are medium-sized and easy to swallow. Shipping to Goa was quick.",
        tags: ["Daily supplement", "Quality"],
      },
    ],
  },
  "moringa-powder": {
    tags: [
      "Smoothies",
      "Energy",
      "Green powder",
      "Nutrition",
      "Quality",
    ],
    reviews: [
      {
        id: "moringa-1",
        author: "Jessica D'Souza",
        verified: true,
        rating: 5,
        date: "03/16/2026",
        title: "Best green addition",
        body: "I blend a teaspoon into my post-workout smoothie. Colour is vibrant green and it doesn't clump if you blend well. Energy feels cleaner than coffee alone.",
        tags: ["Smoothies", "Energy"],
      },
      {
        id: "moringa-2",
        author: "Rajesh Kumar",
        verified: true,
        rating: 5,
        date: "02/22/2026",
        body: "My mother uses moringa traditionally — she approved of the smell and fine grind of this powder. We mix it into dal sometimes. Fresh, earthy aroma.",
        tags: ["Nutrition", "Quality"],
      },
      {
        id: "moringa-3",
        author: "Simran Kaur",
        verified: false,
        rating: 5,
        date: "01/12/2026",
        title: "Morning staple",
        body: "Replaced my expensive imported brand. This is fresher and half the price. Pouch seals tightly — important in humid Mumbai weather.",
        tags: ["Green powder", "Quality"],
      },
      {
        id: "moringa-4",
        author: "Arun Namboothiri",
        verified: true,
        rating: 4,
        date: "12/03/2025",
        body: "Slightly bitter on its own in water — expected for moringa. In curd or smoothie it's perfect. Good micronutrient boost for vegetarian diet.",
        tags: ["Nutrition", "Smoothies"],
      },
      {
        id: "moringa-5",
        author: "Bhavna Patel",
        verified: true,
        rating: 5,
        date: "10/28/2025",
        title: "Kids' nutrition hack",
        body: "I hide half a teaspoon in banana milkshake for my picky eater. No complaints so far. Happy it's organic and lab tested.",
        tags: ["Nutrition", "Quality"],
      },
      {
        id: "moringa-6",
        author: "Karunakar Rao",
        verified: false,
        rating: 5,
        date: "09/05/2025",
        body: "Third reorder. Consistent colour and texture every time. Delivery packaging uses minimal plastic which I appreciate.",
        tags: ["Green powder", "Energy"],
      },
    ],
  },
  "spirulina-powder": {
    tags: [
      "Protein",
      "Stamina",
      "Smoothies",
      "Immunity",
      "Quality",
    ],
    reviews: [
      {
        id: "spirulina-1",
        author: "Gokul",
        verified: true,
        rating: 5,
        date: "03/05/2026",
        title: "Best",
        body: "Quality is so good. Deep green colour, no sandy grit at the bottom of my glass. I take it before gym — stamina feels better on long cardio days.",
        tags: ["Quality", "Stamina"],
      },
      {
        id: "spirulina-2",
        author: "AW",
        verified: true,
        rating: 5,
        date: "02/14/2026",
        title: "Spirulina powder",
        body: "High quality and mixes well in coconut water. I've tried cheaper brands that smelled off — this one smells fresh and algae-clean, not fishy.",
        tags: ["Quality", "Smoothies"],
      },
      {
        id: "spirulina-3",
        author: "Maria Fernandes",
        verified: false,
        rating: 5,
        date: "01/21/2026",
        body: "Plant-based protein source that actually fits my budget. I stir into oats every morning. Skin looks clearer too — might be the nutrition boost.",
        tags: ["Protein", "Smoothies"],
      },
      {
        id: "spirulina-4",
        author: "Harshvardhan Sinha",
        verified: true,
        rating: 4,
        date: "12/18/2025",
        title: "Strong taste",
        body: "You will taste it if you only use water — blend with fruit. Once I figured that out, it's been great. Lab report on the site gave me confidence to buy.",
        tags: ["Smoothies", "Quality"],
      },
      {
        id: "spirulina-5",
        author: "Leela Krishnan",
        verified: true,
        rating: 5,
        date: "11/07/2025",
        title: "Immunity support",
        body: "Whole family takes a small dose during season change. Fewer colds this winter compared to last year. Pouch is easy to store in the fridge.",
        tags: ["Immunity", "Protein"],
      },
      {
        id: "spirulina-6",
        author: "Zaid Ahmed",
        verified: false,
        rating: 5,
        date: "09/29/2025",
        body: "Competitive price for the purity level. Dissolves better than my previous brand from a big marketplace seller. Will stick with Har Ghar Shudhi.",
        tags: ["Quality", "Protein"],
      },
    ],
  },
  "wildforest-multiflora-honey": {
    tags: [
      "Taste",
      "Raw honey",
      "Purity",
      "Family favourite",
      "Quality",
    ],
    reviews: [
      {
        id: "honey-1",
        author: "Sansuk Lyngdoh Nonglait",
        verified: true,
        rating: 5,
        date: "03/19/2026",
        body: "The products are incredible just like their work. This honey tastes like the forest — floral, not overly sweet. My children love it on warm roti.",
        tags: ["Taste", "Family favourite"],
      },
      {
        id: "honey-2",
        author: "Divya Ranganathan",
        verified: true,
        rating: 5,
        date: "02/27/2026",
        title: "Real multiflora honey",
        body: "Crystallised slightly in winter which tells me it's not overheated. Thick, aromatic, perfect in ginger tea when I have a sore throat.",
        tags: ["Raw honey", "Purity"],
      },
      {
        id: "honey-3",
        author: "Manish Tiwari",
        verified: false,
        rating: 5,
        date: "01/15/2026",
        body: "We finished one jar in three weeks. Reordered the larger size. You can taste the difference from supermarket honey — this has depth.",
        tags: ["Taste", "Quality"],
      },
      {
        id: "honey-4",
        author: "Elena D'Mello",
        verified: true,
        rating: 5,
        date: "12/08/2025",
        title: "Gift-worthy",
        body: "Bought as Diwali gifts for relatives. Everyone asked where it was from. Glass jar feels premium and the seal was intact on all six bottles.",
        tags: ["Quality", "Family favourite"],
      },
      {
        id: "honey-5",
        author: "Prakash Yadav",
        verified: true,
        rating: 4,
        date: "10/31/2025",
        body: "Excellent honey. Price is a bit higher than local market but the purity and lab testing justify it for something we eat daily.",
        tags: ["Purity", "Raw honey"],
      },
      {
        id: "honey-6",
        author: "Nandini Bose",
        verified: false,
        rating: 5,
        date: "09/12/2025",
        title: "Morning ritual",
        body: "Warm water, lemon, and a spoon of this honey before yoga. Digestion feels lighter. Love that it's wild-sourced and not blended with syrup.",
        tags: ["Raw honey", "Taste"],
      },
    ],
  },
  "pain-shield": {
    tags: [
      "Muscle relief",
      "Joint comfort",
      "Fast acting",
      "Spray",
      "Recovery",
    ],
    reviews: [
      {
        id: "pain-1",
        author: "Colonel Ravi Anand (Retd.)",
        verified: true,
        rating: 5,
        date: "03/07/2026",
        title: "Knee discomfort eased",
        body: "Old sports injury flares up in cold weather. Two sprays and a light rub — cooling relief within minutes. Non-greasy so I can dress immediately after.",
        tags: ["Joint comfort", "Fast acting"],
      },
      {
        id: "pain-2",
        author: "Shalini Gupta",
        verified: true,
        rating: 5,
        date: "02/01/2026",
        body: "Keep this in my gym bag for shoulder stiffness after swimming. Ayurvedic smell is mild, not overpowering like some menthol balms.",
        tags: ["Muscle relief", "Recovery"],
      },
      {
        id: "pain-3",
        author: "Joseph Mathew",
        verified: false,
        rating: 4,
        date: "12/22/2025",
        title: "Works for back strain",
        body: "Desk job back pain — helps for a few hours at a time. I reapply after lunch. Wish the bottle was slightly larger for daily use.",
        tags: ["Muscle relief", "Spray"],
      },
      {
        id: "pain-4",
        author: "Ayesha Siddiqui",
        verified: true,
        rating: 5,
        date: "11/11/2025",
        body: "My mother uses it on her wrists before gardening. She prefers spray over sticky ointments. Bottle fits in her apron pocket.",
        tags: ["Joint comfort", "Spray"],
      },
      {
        id: "pain-5",
        author: "Venkat Raman",
        verified: true,
        rating: 5,
        date: "09/18/2025",
        title: "Post-run essential",
        body: "Marathon training beats up my calves. This plus foam rolling gets me ready for the next day. Absorbs quickly — no stain on clothes.",
        tags: ["Recovery", "Fast acting"],
      },
      {
        id: "pain-6",
        author: "Komal Bansal",
        verified: false,
        rating: 5,
        date: "08/02/2025",
        body: "Ordered for neck tension from long drives. Cooling effect is immediate. Natural ingredients list — my pharmacist had no concerns.",
        tags: ["Muscle relief", "Fast acting"],
      },
    ],
  },
};

export function getProductReviewsBundle(slug: string): ProductReviewsBundle | null {
  return REVIEWS_BY_SLUG[slug] ?? null;
}

export function ratingDistribution(
  average: number,
  total: number,
): [number, number, number, number, number] {
  const fiveStar = Math.round(total * (average >= 4.85 ? 0.86 : average >= 4.7 ? 0.78 : 0.68));
  const fourStar = Math.round(total * (average >= 4.85 ? 0.11 : 0.16));
  const threeStar = Math.max(0, total - fiveStar - fourStar);
  return [fiveStar, fourStar, threeStar, 0, 0];
}
